@ShoppingCartStartedKata_HostAddress = http://localhost:5275

GET {{ShoppingCartStartedKata_HostAddress}}/availableProducts/
Accept: application/json

###

GET {{ShoppingCartStartedKata_HostAddress}}/showCartContent/
Accept: application/json

###

POST {{ShoppingCartStartedKata_HostAddress}}/addProduct/
Content-Type: application/json

{
  "id": "0",
  "name": "Potato",
  "price": "1.5"
}

###
